import Navbar from '../../components/commons/Navbar';
import Header from '../../components/commons/Header';
import Footer from '../../components/commons/Footer';
import Head from 'next/head';

export const getStaticPaths = async () => {
	const res = await fetch('http://localhost:3004/items');
	const data = await res.json();
	
	const paths = data.map(item => {
		return {
			params: {id: item.id.toString()},
		}
	})

	return {
		paths,
		fallback: false,
	}
}

export const getStaticProps = async (context) => {
	const id = context.params.id;
	const res = await fetch(`http://localhost:3004/items/${id}`);
	const data = await res.json();

	return {
		props: {item: data},
	}
}

const Details = ({item}) => {
	return (
		<>
			<Head>
				<title>Detail</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<Navbar/>
			<Header place={item.name_place} locality={item.locality} openHour={item.open_hour}
			openMonth={item.open_month} closeMonth={item.close_month}
					closeHour={item.close_hour} src={item.src}
					period={item.period}
					accessibleStyle={(item.accessible === true ? 'badge-success' : 'badge-danger')}/>

				<div className='flex flex-row justify-around mt-10 mb-20'>
					<div className='p-4 flex flex-col gap-2'>
						<h3 className='text-4xl'>I Sentieri</h3>
						{item.tracks.map((track) => (
							<p>{track.name_track} - {track.hour_track} - {track.difficulty}</p>
						))}
					</div>
					<div className='p-4 flex flex-col gap-2'>
						<h3 className='text-4xl'>Il Menu</h3>
						<p>{item.menu}</p>
						<p>Specialità della casa: {item.menu_special}</p>
					</div>
				</div>
			<Footer/>
		</>
	);
}

export default Details;