import Head from 'next/head'
import Navbar from '../components/commons/Navbar';
import Button from '../components/ui/Button';
import Badge from '../components/ui/Badge';
import Footer from '../components/commons/Footer';
import Card from '../components/ui/Card';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Utility repo</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<Navbar/>
			<div className="m-8 flex flex-row justify-around">
				<Button text="Primary" className="button-primary"/>
				<Button text="Secondary" className="button-secondary"/>
			</div>
			<div className="m-8 flex flex-row justify-around">
				<Badge text="Success" className="badge-success"/>
				<Badge text="Oh no" className="badge-danger"/>
			</div>
			<div className="m-10 grid md:grid-cols-3 gap-8">
				<Card title="To Dummy Data" description="Just a card"
					  href="dummyDataPage/"
					  src="https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60"/>
			</div>
			<div>
				<Footer/>
			</div>
		</div>
	)
}

